import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { webcrypto } from 'node:crypto';
const workspace = process.cwd();
const sandbox = await fs.mkdtemp(path.join(os.tmpdir(), 'blog-workflow-'));
const site = path.join(sandbox, 'site');
const source = path.join(sandbox, 'obsidian');
await fs.mkdir(site); await fs.mkdir(source);
await fs.cp(path.join(workspace, 'scripts'), path.join(site, 'scripts'), { recursive: true });
await fs.symlink(path.join(workspace, 'node_modules'), path.join(site, 'node_modules'));
await fs.mkdir(path.join(site, 'content/blogs'), { recursive: true });
const password = 'fixture-password-long-2026';
await fs.writeFile(path.join(site, '.blog-local.json'), JSON.stringify({ sharedPassword: password }));
const article = (title, slug, locked, draft, body) => `---\ntitle: ${title}\nslug: ${slug}\ntags: [测试]\nlocked: ${locked}\ndraft: ${draft}\n---\n\n${body}\n`;
const sync = (expectedSuccess = true) => {
 const result = spawnSync(process.execPath, [path.join(site, 'scripts/sync-blog.mjs'), '--source', source], { cwd: site, encoding: 'utf8', env: { ...process.env, BLOG_PASSWORD: 'ignored-env-password-2026' } });
 assert.equal(result.status === 0, expectedSuccess, result.stderr);
};
const registry = path.join(site, 'app/blogs/posts.json');
await fs.writeFile(path.join(source, 'public.md'), article('公开标题', 'public-post', false, false, '## 标题\n\n[文字链接](https://example.com/)'));
await fs.writeFile(path.join(source, 'private.md'), article('私密标题', 'private-post', true, false, 'fixture-secret-body'));
await fs.writeFile(path.join(source, 'draft.md'), article('草稿', 'draft-post', false, true, 'fixture-draft-body'));
sync();
const first = await fs.readFile(registry, 'utf8');
const posts = JSON.parse(first);
assert.equal(posts.length, 2);
assert.equal(posts.find(p => p.slug === 'public-post').title, '公开标题');
assert.equal(posts.find(p => p.slug === 'public-post').locked, false);
assert.equal(posts.find(p => p.slug === 'private-post').locked, true);
assert.ok(!first.includes('fixture-secret-body') && !first.includes('fixture-draft-body') && !first.includes(password));
const files = await fs.readdir(path.join(site, 'content/blogs'));
assert.deepEqual(files.sort(), ['private-post.locked.json', 'public-post.md']);
const encrypted = posts.find(p => p.slug === 'private-post').encrypted;
const bytes = value => Buffer.from(value, 'base64');
async function decrypt(pw, data = encrypted) {
 const material = await webcrypto.subtle.importKey('raw', new TextEncoder().encode(pw), 'PBKDF2', false, ['deriveKey']);
 const key = await webcrypto.subtle.deriveKey({ name:'PBKDF2', salt:bytes(data.salt), iterations:data.iterations, hash:'SHA-256' }, material, { name:'AES-GCM', length:256 }, false, ['decrypt']);
 return new TextDecoder().decode(await webcrypto.subtle.decrypt({ name:'AES-GCM', iv:bytes(data.iv) }, key, bytes(data.ciphertext)));
}
assert.equal(await decrypt(password), 'fixture-secret-body');
await assert.rejects(() => decrypt('incorrect-password'));
sync(); assert.equal(await fs.readFile(registry, 'utf8'), first);
await fs.writeFile(path.join(source, 'invalid.md'), article('错误类型', 'invalid-post', 'public', false, '不应发布'));
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), first);
await fs.rm(path.join(source, 'invalid.md'));
await fs.writeFile(path.join(source, 'invalid.md'), article('字符串类型', 'invalid-post', '"false"', false, '不应发布'));
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), first);
await fs.rm(path.join(source, 'invalid.md'));
const localConfig = JSON.parse(await fs.readFile(path.join(site, '.blog-local.json'), 'utf8'));
assert.equal(localConfig.sharedPassword, password);
assert.equal((await fs.stat(path.join(site, '.blog-local.json'))).mode & 0o777, 0o600);
const rotatedPassword = 'fixture-rotated-password-2026';
await fs.writeFile(path.join(site, '.blog-local.json'), JSON.stringify({ ...localConfig, sharedPassword: rotatedPassword }));
sync();
const rotatedRegistry = await fs.readFile(registry, 'utf8');
const rotated = JSON.parse(rotatedRegistry).find(p => p.slug === 'private-post').encrypted;
assert.equal(await decrypt(rotatedPassword, rotated), 'fixture-secret-body');
await assert.rejects(() => decrypt(password, rotated));
assert.ok(!rotatedRegistry.includes(rotatedPassword));
sync(); assert.equal(await fs.readFile(registry, 'utf8'), rotatedRegistry);
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', false, false, '正文已更新'));
sync(); assert.ok((await fs.readFile(registry, 'utf8')).includes('正文已更新'));
await fs.writeFile(path.join(source, 'duplicate.md'), article('重复', 'public-post', false, false, '重复'));
const beforeDuplicate = await fs.readFile(registry, 'utf8');
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), beforeDuplicate);
await fs.rm(path.join(source, 'duplicate.md'));
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', true, false, '正文已更新'));
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), beforeDuplicate);
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', false, true, '正文已更新'));
await fs.rm(path.join(source, 'private.md'));
sync(); assert.deepEqual(JSON.parse(await fs.readFile(registry, 'utf8')), []);
await fs.rm(sandbox, { recursive: true, force: true });
console.log('通过：公开同步、Markdown 保留、私密加密、正确/错误密码、重复同步、内容修改、草稿/删除撤下、重复 slug 、公开转私密保护、统一密码及密码变更后重新加密。');
