import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { webcrypto } from 'node:crypto';
const workspace = process.cwd();
const sandbox = await fs.mkdtemp(path.join(os.tmpdir(), 'blog-workflow-'));
const site = path.join(sandbox, 'site');
const source = path.join(sandbox, 'obsidian');
await fs.mkdir(site); await fs.mkdir(source);
await fs.cp(path.join(workspace, 'scripts'), path.join(site, 'scripts'), { recursive: true });
await fs.symlink(path.join(workspace, 'node_modules'), path.join(site, 'node_modules'));
await fs.mkdir(path.join(site, 'content/blogs'), { recursive: true });
const password = 'fixture-password-long-2026';
const article = (title, slug, visibility, draft, body) => `---\ntitle: ${title}\nslug: ${slug}\ntags: [测试]\nvisibility: ${visibility}\ndraft: ${draft}\n---\n\n${body}\n`;
const sync = (expectedSuccess = true) => {
 const result = spawnSync(process.execPath, [path.join(site, 'scripts/sync-blog.mjs'), '--source', source], { cwd: site, encoding: 'utf8', env: { ...process.env, BLOG_PASSWORD: password } });
 assert.equal(result.status === 0, expectedSuccess, result.stderr);
};
const registry = path.join(site, 'app/blogs/posts.json');
await fs.writeFile(path.join(source, 'public.md'), article('公开标题', 'public-post', 'public', false, '## 标题\n\n[文字链接](https://example.com/)'));
await fs.writeFile(path.join(source, 'private.md'), article('私密标题', 'private-post', 'locked', false, 'fixture-secret-body'));
await fs.writeFile(path.join(source, 'draft.md'), article('草稿', 'draft-post', 'public', true, 'fixture-draft-body'));
sync();
const first = await fs.readFile(registry, 'utf8');
const posts = JSON.parse(first);
assert.equal(posts.length, 2);
assert.equal(posts.find(p => p.slug === 'public-post').title, '公开标题');
assert.ok(!first.includes('fixture-secret-body') && !first.includes('fixture-draft-body') && !first.includes(password));
const files = await fs.readdir(path.join(site, 'content/blogs'));
assert.deepEqual(files.sort(), ['private-post.locked.json', 'public-post.md']);
const encrypted = posts.find(p => p.slug === 'private-post').encrypted;
const bytes = value => Buffer.from(value, 'base64');
async function decrypt(pw) {
 const material = await webcrypto.subtle.importKey('raw', new TextEncoder().encode(pw), 'PBKDF2', false, ['deriveKey']);
 const key = await webcrypto.subtle.deriveKey({ name:'PBKDF2', salt:bytes(encrypted.salt), iterations:encrypted.iterations, hash:'SHA-256' }, material, { name:'AES-GCM', length:256 }, false, ['decrypt']);
 return new TextDecoder().decode(await webcrypto.subtle.decrypt({ name:'AES-GCM', iv:bytes(encrypted.iv) }, key, bytes(encrypted.ciphertext)));
}
assert.equal(await decrypt(password), 'fixture-secret-body');
await assert.rejects(() => decrypt('incorrect-password'));
sync(); assert.equal(await fs.readFile(registry, 'utf8'), first);
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', 'public', false, '正文已更新'));
sync(); assert.ok((await fs.readFile(registry, 'utf8')).includes('正文已更新'));
await fs.writeFile(path.join(source, 'duplicate.md'), article('重复', 'public-post', 'public', false, '重复'));
const beforeDuplicate = await fs.readFile(registry, 'utf8');
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), beforeDuplicate);
await fs.rm(path.join(source, 'duplicate.md'));
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', 'locked', false, '正文已更新'));
sync(false); assert.equal(await fs.readFile(registry, 'utf8'), beforeDuplicate);
await fs.writeFile(path.join(source, 'public.md'), article('修改标题', 'public-post', 'public', true, '正文已更新'));
await fs.rm(path.join(source, 'private.md'));
sync(); assert.deepEqual(JSON.parse(await fs.readFile(registry, 'utf8')), []);
await fs.rm(sandbox, { recursive: true, force: true });
console.log('通过：公开同步、Markdown 保留、私密加密、正确/错误密码、重复同步、内容修改、草稿/删除撤下、重复 slug 和公开转私密保护。');
